### ISSUE TITLE
"ReferenceError: WebSocket is not defined" when using createLongLivedTokenAuth

### ISSUE THREAD

**Issue by erikmuttersbach** [home-assistant/home-assistant-js-websocket#440]
When I am trying to run the example code for using a long lived token, I get an error in socket.js:

Code:
```js
const auth = createLongLivedTokenAuth(
    this.host,
    this.token
);

this.wsConnection = await createConnection({ auth });
```

Error:
```
Exception has occurred: ReferenceError: WebSocket is not defined
  at connect (file:///Users/erikmuttersbach/Projects/home-assistant-openai-2/node_modules/home-assistant-js-websocket/dist/socket.js:34:24)
    at file:///Users/erikmuttersbach/Projects/home-assistant-openai-2/node_modules/home-assistant-js-websocket/dist/socket.js:103:45
    at new Promise (<anonymous>)
    at Object.createSocket (file:///Users/erikmuttersbach/Projects/home-assistant-openai-2/node_modules/home-assistant-js-websocket/dist/socket.js:103:12)
    at createConnection (file:///Users/erikmuttersbach/Projects/home-assistant-openai-2/node_modules/home-assistant-js-websocket/dist/index.js:16:38)
    at HomeAssistant.connect (file:///Users/erikmuttersbach/Projects/home-assistant-openai-2/dist/homeassistant.js:29:35)
    at assistant (file:///Users/erikmuttersbach/Projects/home-assistant-openai-2/dist/assistant.js:59:14)
    at file:///Users/erikmuttersbach/Projects/home-assistant-openai-2/dist/assistant.js:175:1
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
```

Screenshot for context
![Screenshot 2023-11-09 at 23 37 29](https://github.com/home-assistant/home-assistant-js-websocket/assets/1399523/8703aa6a-758c-42d0-bbbe-3323d0ef6e22)

Environment:
- Node 21.1.0
- home-assistant-js-websocket version 10.2.0

**Comment by erikmuttersbach** [comment]
Should have read the docs ;) 

![Screenshot 2023-11-09 at 23 42 26](https://github.com/home-assistant/home-assistant-js-websocket/assets/1399523/07d7e9da-c842-4a6f-8521-3271d679dd94)
