### ISSUE TITLE
`ReferenceError: location is not defined` on very simple example

### ISSUE THREAD

**Issue by stefaanv** [home-assistant/home-assistant-js-websocket#444]
Trying out this library without much success.
I get an `UnhandledPromiseRejection` with the below code. 
Sniffing the network while running the code shows that there is no network traffik to my HASS instance.
Full error message below

Program code:
```typescript
async function connect() {
  let auth
  try {
    // Try to pick up authentication after user logs in
    auth = await getAuth({ hassUrl: 'http://192.168.0.3' })
  } catch (err) {
    console.error(err)
  }
  const connection = await createConnection({ auth })
  subscribeEntities(connection, ent => console.log(ent))
}

connect()
```

```
ReferenceError: location is not defined
    at genClientId (C:\Users\stefa\Documents\projecten\hass-websocket-test\node_modules\home-assistant-js-websocket\dist\haws.cjs:535:27)
    at getAuth (C:\Users\stefa\Documents\projecten\hass-websocket-test\node_modules\home-assistant-js-websocket\dist\haws.cjs:675:74)
    at C:\Users\stefa\Documents\projecten\hass-websocket-test\dist\main.js:26:68
    at Generator.next (<anonymous>)
    at C:\Users\stefa\Documents\projecten\hass-websocket-test\dist\main.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\stefa\Documents\projecten\hass-websocket-test\dist\main.js:4:12)
    at connect (C:\Users\stefa\Documents\projecten\hass-websocket-test\dist\main.js:22:12)
    at Object.<anonymous> (C:\Users\stefa\Documents\projecten\hass-websocket-test\dist\main.js:35:1)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
Waiting for the debugger to disconnect...
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "4".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v20.5.1
```

**Comment by shannonhochkins** [comment]
I'm assuming you're using nextjs, you need to use this in the context of the client

**Comment by stefaanv** [comment]
Oops, I'm using this library on the backend in a nestjs project.
Got it working now though !
Is this not the intended use ?  Maybe that should be mentioned more explicitly in the documentation

**Comment by balloob** [comment]
You can only use the connection, not the auth part as that is frontend. NodeJS documentation is in the README https://github.com/home-assistant/home-assistant-js-websocket?tab=readme-ov-file#using-this-in-nodejs
