### ISSUE TITLE
Unhandled Promise Rejection after a reconnection and trying to resubscribe to events

### ISSUE THREAD

**Issue by zachowj** [home-assistant/home-assistant-js-websocket#59]
Getting an unhandled promise rejection when it's resubscribing to events after a reconnect and the socket drops the connection.

https://github.com/home-assistant/home-assistant-js-websocket/blob/5d14aee9cae755d4cc9f5db2d2a82d89ddcb544d/lib/connection.ts#L156-L159

Getting two different errors seems to be a race condition on which one gets thrown.

**First One**:

This is referencing the above SendMessagePromise
```
UnhandledPromiseRejectionWarning: Error: WebSocket is not open: readyState 2 (CLOSING)
    at WebSocket.send (/opt/node_modules/node-red-contrib-home-assistant-websocket/node_modules/ws/lib/websocket.js:314:19)
    at e.sendMessage (/opt/node_modules/home-assistant-js-websocket/dist/haws.umd.js:1:3458)
    at /opt/node_modules/home-assistant-js-websocket/dist/haws.umd.js:1:3630
    at new Promise (<anonymous>)
    at e.sendMessagePromise (/opt/node_modules/home-assistant-js-websocket/dist/haws.umd.js:1:3546)
    at p (/opt/node_modules/home-assistant-js-websocket/dist/haws.umd.js:1:8102)
    at w (/opt/node_modules/home-assistant-js-websocket/dist/haws.umd.js:1:8802)
    at /opt/node_modules/home-assistant-js-websocket/dist/haws.umd.js:1:7847
    at /opt/node_modules/home-assistant-js-websocket/dist/haws.umd.js:1:1440
    at Object.next (/opt/node_modules/home-assistant-js-websocket/dist/haws.umd.js:1:1545)
```

**Second One**:

https://github.com/home-assistant/home-assistant-js-websocket/blob/5d14aee9cae755d4cc9f5db2d2a82d89ddcb544d/lib/connection.ts#L244-L250

**Context**:

Using [node-red-contrib-home-assistant-websocket](https://github.com/zachowj/node-red-contrib-home-assistant-websocket) within [hass.io](https://github.com/home-assistant/hassio) and the [addon-node-red](https://github.com/hassio-addons/addon-node-red). Everything works fine with the connection until you reboot hass.io and the addon is trying to reconnect. While trying to reconnect to Home Assistant it connects and disconnects from the hass.io proxy several times that's when the errors are getting thrown.

**Comment by balloob** [comment]
It's weird is that `sendMessagePromise` fails after a reconnect, because I would have expected it to fail already when trying to handle the auth phase (which is being done as part of `createSocket`.

Did you upgrade your `ws` dependency to [the latest version](https://github.com/websockets/ws/releases/tag/6.1.0) so it properly handles the `close` event?

**Comment by zachowj** [comment]
The latest `ws` update was not for the client side it was for the server side. But yes all the dependencies are up to date.

I mocked up a sample app, [zachowj/hajw-test](https://github.com/zachowj/hajw-test), that throws the second error. I can't seem to replicate the first one with any consistency but only one ever happens not both at the same time.

```
[Client][Auth Phase] Initializing ws://127.0.0.1:8080
[Client][Auth Phase] New connection ws://127.0.0.1:8080
[Server] Sending need auth
[Client][Auth Phase] Received { type: 'auth_required', ha_version: '0.80.3' }
[Server] received: {"type":"auth","api_password":"abc"}
[Client][Auth Phase] Received { type: 'auth_ok', ha_version: '0.80.3' }
[Client] Sending SubscribeEntities
[Server] received: {"type":"subscribe_events","event_type":"state_changed","id":2}
[Server] Closing Connection to Client
[Server] received: {"type":"get_states","id":3}
[Client][UnhandledRejection] { type: 'result',
  success: false,
  error: { code: 3, message: 'Connection lost' } }
[Client][UnhandledRejection] { type: 'result',
  success: false,
  error: { code: 3, message: 'Connection lost' } }
[Client][Auth Phase] Initializing ws://127.0.0.1:8080
[Client][Auth Phase] New connection ws://127.0.0.1:8080
[Server] Sending need auth
[Client][Auth Phase] Received { type: 'auth_required', ha_version: '0.80.3' }
[Server] received: {"type":"auth","api_password":"abc"}
[Client][Auth Phase] Received { type: 'auth_ok', ha_version: '0.80.3' }
[Server] received: {"type":"get_states","id":2}
```

It happens when the client connects and authorizes with the server. Then sends [SubscribeEntities](https://github.com/zachowj/hajw-test/blob/ebb89d96bb1b41b953c91d19108febeb76668c26/index.js#L141) to the server.
```
{"type":"subscribe_events","event_type":"state_changed","id":2}
{"type":"get_states","id":3}
```
At this point, the client is expecting the server to respond with a results message. If the server [closes the connection](https://github.com/zachowj/hajw-test/blob/ebb89d96bb1b41b953c91d19108febeb76668c26/index.js#L31-L35) before sending the result message the reject gets thrown in the [socket close handler](https://github.com/home-assistant/home-assistant-js-websocket/blob/5d14aee9cae755d4cc9f5db2d2a82d89ddcb544d/lib/connection.ts#L244-L250).

A possible fix would be wrapping the [SendMessagePromise](https://github.com/home-assistant/home-assistant-js-websocket/blob/5d14aee9cae755d4cc9f5db2d2a82d89ddcb544d/lib/connection.ts#L156-L159) in a try/catch, not sure if that the correct fix.

Also another thing I noticed while mocking it up was that on the first connection the SubscribeEntities sends both
```
{"type":"subscribe_events","event_type":"state_changed","id":2}
{"type":"get_states","id":3}
```
to the server but after the rejection error any reconnect atempts after that the SubscribeEntites only sends `{"type":"get_states","id":2}` not actually both commands to the server.

**Comment by zachowj** [comment]
Was able to replicate the first error by having the server close the socket right after sending `auth_ok` message.

Working Example [zachowj/hajw-test/tree/error1](https://github.com/zachowj/hajw-test/tree/error1)

Each error is dependent on when the connection gets closed from the server.

**Comment by balloob** [comment]
The subscribe to events should be automatically redone by the connection class: https://github.com/home-assistant/home-assistant-js-websocket/blob/5d14aee9cae755d4cc9f5db2d2a82d89ddcb544d/lib/connection.ts#L99-L105

If that doesn't work, let's break it out into another issue. But let's first solve current one, as that might fix both.

**Comment by balloob** [comment]
Aaah no, I see now that you're right.

We should not reject in-flight subscribeEvents commands in `handleClose`, because we are able to recover those.

**Comment by balloob** [comment]
hmm no, we should never reject a subscribeEvents in flight, because we don't store a `reject` in the command in flight.

Let me open a PR to add some types so it makes more sense.

**Comment by balloob** [comment]
aah okay, I think I know what's going on.

As part of subscribeEvents, we use `sendMessagePromise`, which is the one that is rejecting: https://github.com/home-assistant/home-assistant-js-websocket/blob/5d14aee9cae755d4cc9f5db2d2a82d89ddcb544d/lib/connection.ts#L156-L159

And that makes it so that we don't retry either, as we never got to the point of storing our info in `this.commands`

**Comment by balloob** [comment]
PR to add some more types https://github.com/home-assistant/home-assistant-js-websocket/pull/61

**Comment by balloob** [comment]
PR to solve problem 2 up in #62

**Comment by balloob** [comment]
PR to solve problem 1 in #63

**Comment by balloob** [comment]
Did it solve it?

**Comment by zachowj** [comment]
It has fixed the first issue and it does resubscription to the correct events on a reconnect but I am still seeing an unhandled rejection when using .subscribeEntities or .subscribeEvents when the server disconnects before sending back a result.

Sorry, haven't had a chance to look into it further.

**Comment by zachowj** [comment]
Not sure if I should have opened a new issue for this but here goes.

Since `subscribeEvents` returns  `info.unsubscribe` and not the promise there is no way to catch a rejection from the promise inside. This rejection occurs when the promise in `subscribeEvents` is called and has not been resolved by the time the connection is closed. The `_handleClose` is where the reject is thrown.

https://github.com/home-assistant/home-assistant-js-websocket/blob/2bc4cac3491e2c6aaddf2b1602af9495536eca7c/lib/connection.ts#L169-L200

A simple solution is to just use a `.catch(() => {})` on the promise. The same reasoning can be used here as you did for the `SendMessage` try/catch block in the promise
```
// Happens when the websocket is already closing.
// Don't have to handle the error, reconnect logic will pick it up.
```
